version: "2"
run:
  concurrency: 8
  timeout: 5m
  issues-exit-code: 1
  tests: true
linters:
  default: none
  enable:
    - errcheck
    - goconst
    - gocritic
    - gocyclo
    # - gosimple
    - govet
    - ineffassign
    - nakedret
    - prealloc
    - staticcheck
    # - stylecheck
    - unconvert
    - unparam
    - unused
  settings:
    dupl:
      threshold: 200
    errcheck:
      check-blank: true
    govet:
      enable:
        - shadow
    funlen:
      lines: 80
      statements: 50
    gocognit:
      min-complexity: 30
    gocyclo:
      min-complexity: 20
    nakedret:
      max-func-lines: 50
    staticcheck:
      checks:
        - "all"
        - "-SA6000"
        - "-QF1001"
        - "-SA2002"
    stylecheck:
      checks: ["all", "-ST1018"]
      initialisms:
        [
          "ACL",
          "API",
          "ASCII",
          "CPU",
          "CSS",
          "DNS",
          "EOF",
          "GUID",
          "HTML",
          "HTTP",
          "HTTPS",
          "ID",
          "IP",
          "JSON",
          "QPS",
          "RAM",
          "RPC",
          "SLA",
          "SMTP",
          "SQL",
          "SSH",
          "TCP",
          "TLS",
          "TTL",
          "UDP",
          "UI",
          "GID",
          "UID",
          "UUID",
          "URI",
          "URL",
          "UTF8",
          "VM",
          "XML",
          "XMPP",
          "XSRF",
          "XSS",
          "CSV",
        ]
    golint:
      min-confidence: 0.8

  exclusions:
    generated: lax
    presets:
      - comments
      - common-false-positives
      - legacy
      - std-error-handling
    rules:
      - path: (.+)\.go$
        text: should have comment
      - path: (.+)\.go$
        text: always receives
      - path: (.+)\.go$
        text: parameter .* is always
      - path: (.+)\.go$
        text: comment on exported .* should be of the form
    paths:
      - "bin$"
      - "\\.git$"
      - "misc$"
      - "spec$"
      - "pkg$"
      - "common$"
      - "_easyjson.go"
      - "jwt_example.go"
      - "pb.go"
issues:
  max-issues-per-linter: 0
  max-same-issues: 0
formatters:
  enable:
    - gofmt
  settings:
    gofmt:
      simplify: true
  exclusions:
    generated: lax
